apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector: 
    app: story
  ports:
    - protocol: 'TCP'
      port: 80   # to be exposed
      targetPort: 3000  # my application is listening on
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer